### ISSUE TITLE
nrfjprog fails when using only pyocd (cmsis-dap jtag interface)

### ISSUE THREAD

**Issue by PontusO** [mjdietzx/nrfjprog#20]
When trying to use nrfjprog without having the SEGGER libraries installed it fails when trying to locate the libraries. I discovered this when trying to use the utility with my cmsis-dap adapter.

**Comment by mjdietzx** [comment]
in the latest source code pyOCD is supported:

just add the --daplink argument to whatever command you use.

so $python nrfjprog_cli.py erase --daplink

I just added this feature so a lot more to do and this isnt stable. you will need to use the latest soruce (I haven't built and released exes with this functionality yet - planned in a few days). may have pyOCD vs pynrfjprog automatically detected in future
