### ISSUE TITLE
Feature request: put SEGGER path as a variable when calling nrfjprog

### ISSUE THREAD

**Issue by luisonoff** [mjdietzx/nrfjprog#23]
We asked Nordic about this request a few months ago, they told us that this feature would be considered for future nrfjprog releases? Is it already in? Or could it be added sometime soon?
We could offer our help to test it.

The feature is just to add a new variable when calling nrfjprog where you can indicate the SEGGER local folder, in case it is not the default folder. This allows for fully independent/portable programming enviroments for nRF5 MCUs.

Thank you!

**Comment by mjdietzx** [comment]
OK, so you want to be able to specify where exactly to look for `JLinkARM.dll`?

By default [pynrfjprog](https://github.com/NordicSemiconductor/pynrfjprog/blob/master/pynrfjprog/API.py#L197) looks for `JLinkARM.dll` in the default installation directory for SEGGER/Jlink but this can easily be changed so you can specify this path.

Please note I will implement this here, but if you are using the official [nrfjprog](https://www.nordicsemi.com/eng/nordic/Products/nRF51822/nRF5x-Command-Line-Tools-Win32/33444) this is not supported currently.

**Comment by mjdietzx** [comment]
Done: https://github.com/NordicSemiconductor/nRF5-universal-prog/commit/114aac084318c6d24ac2bbdb3b167c4b4e09ff03

To use: `$ python -m nrfjprog erase --jlink_arm_dll_path "~/Downloads/JLinkARM.dll"`

This argument can be specified with every command.

**Comment by luisonoff** [comment]
Great! Thank you very much!
How can I test it?
Could you make a new release with this change?

**Comment by mjdietzx** [comment]
Are you running the tool from python or as a .exe? If running from python just update the source code and follow instructions in readme `$ python nrfjprog_cli.py erase --jlink_arm_dll_path "JLinkARM.dll"`.  If you run this as a .exe I can do another release. Are you windows, osx or linux? 

Also make sure you understand this tool isn't officially supported, and you should be using [nrfjprog](https://www.nordicsemi.com/eng/nordic/Products/nRF51822/nRF5x-Command-Line-Tools-Win32/33444) for a stable tool. But for your use case this tool should be OK, and also you'd have to request this feature to be added to the official nrfjprog which would take time.

**Comment by luisonoff** [comment]
We are using it as an exe from eclipse. We use windows 10 64 bits.
We understand this is an experimental version of nrfjprog with no support. But we were also told that this version will replace the official one sometime rigth?
Thank you!

**Comment by mjdietzx** [comment]
OK, I will build this as an exe for windows and release it. Let me know if it works ok.

Originally it was the hope that this become official at some point, but that is not the case anymore. You could always request this feature for the official version through support and use nRF5-universal-prog as a temporary solutino until that feature is implemented.

**Comment by mjdietzx** [comment]
Released here: https://github.com/NordicSemiconductor/nRF5-universal-prog/releases/tag/v0.0.4-alpha

**Comment by gamnes** [comment]
Hi liusonoff,
The feature you are requesting is already available in the official nrfjprog.exe, but it currently added as a "hidden" option of the tool. To use it, provide the argument --jdll PATHINCLUDINGNAME.dll when calling a command. If you are going to use it, we will make it public in the next release, but as I said, it is already supported and has been for some time.
